name: Test Git Push

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  # отключаем встроенный токен, чтобы использовать URL

      - name: Create test file
        run: echo "GitHub Actions push test" > push-test.txt

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add push-test.txt
          git commit -m "Test push from Actions" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/aaviis/aaviis.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
