name: Update GitHub Stats

# Когда запускать workflow: каждый день или вручную
on:
  schedule:
    - cron: '0 0 * * *' # каждый день в 00:00 UTC
  workflow_dispatch: # возможность запускать вручную

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub stats images
        run: |
          curl -o ./stats/README-stats.svg "https://github-readme-stats.vercel.app/api?username=aaviis&show_icons=true&theme=tokyonight&include_all_commits=true&count_private=true&token=${{ secrets.GS_TOKEN }}"
          curl -o ./stats/README-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=aaviis&layout=compact&theme=tokyonight&count_private=true&exclude_repo=QuantLib,okx,data-science-interview-questions-and-answers&token=${{ secrets.GS_TOKEN }}"
      - name: Commit stats images
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stats/*.svg
          git commit -m "Update GitHub stats" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
